# ports: HOST:CONTAINER
services:
  go:
    build: .
    container_name: ${APP_NAME}-go
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${APP_URL}
      - VIRTUAL_PORT=80
    depends_on:
      - mongo
    ports:
      - 8082:80
    networks:
      - internal
    develop:
      watch:
        - action: sync
          path: ./
          target: /
          ignore:
            - .git/
            - .idea/
            - mongo/

  mongo:
    image: mongo
    container_name: ${APP_NAME}-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_EXPOSE_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - VIRTUAL_HOST=${DB_URL}
      - VIRTUAL_PORT=27017
    volumes:
      - ./mongo/data:/data/db
    networks:
      - internal


networks:

  internal:
    name: lemp-network-${APP_NAME}
    driver: bridge